name: run hippo

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: npm install
      run: npm install
    - name: npm start
      run: npm start
      env:
        POSTGRES_URI: ${{ secrets.POSTGRES_URI }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        CC_USERS: ${{ secrets.CC_USERS }}
